version: '3'
services: 
  db:
    image: postgres:9.5
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  django_project:
    build: .
    command: python manage.py migrate
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/project
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  postgres_data:
